/**
 * Destinations Parser
 * Parses and creates destination documents
 */

export function parseDestinations() {
  return [
    {
      title: 'Merzouga & Erg Chebbi',
      slug: { current: 'merzouga-erg-chebbi' },
      description: `Merzouga, located at the edge of the Erg Chebbi dunes, is a gateway to the Sahara Desert. Experience sunrise and sunset camel trekking across golden sands, sandboarding, and immersive stays in luxury desert camps. The area is perfect for desert photography, stargazing, and exploring the life of Berber nomads.`,
      highlights: [
        'Erg Chebbi golden dunes',
        'Sunrise and sunset camel trekking',
        'Luxury desert camps',
        'Sandboarding opportunities',
        'Desert photography',
        'Stargazing',
        'Berber nomad experiences',
      ],
      activities: [
        'Camel trekking',
        'Sandboarding',
        'Desert camping',
        'Photography',
        'Stargazing',
        '4x4 desert excursions',
      ],
      seoKeywords: 'Merzouga Morocco, Erg Chebbi dunes, camel trekking Merzouga, Sahara desert tours, desert photography Morocco',
      order: 1,
    },
    {
      title: 'Erg Chigaga Desert',
      slug: { current: 'erg-chigaga-desert' },
      description: `Discover Morocco's most remote desert, Erg Chigaga, with towering dunes and untouched landscapes. Ideal for adventurous travelers, Erg Chigaga offers sunset camel rides, off-road 4x4 desert excursions, sandboarding, and luxury camping experiences in the heart of the Sahara.`,
      highlights: [
        'Most remote desert in Morocco',
        'Towering dunes',
        'Untouched landscapes',
        'Off-road 4x4 adventures',
        'Luxury camping',
        'Remote desert experience',
      ],
      activities: [
        'Camel trekking',
        '4x4 desert excursions',
        'Sandboarding',
        'Luxury camping',
        'Desert exploration',
        'Photography',
      ],
      seoKeywords: 'Erg Chigaga Morocco, Sahara adventure tours, Moroccan desert camping, camel trekking Erg Chigaga, desert exploration Morocco',
      order: 2,
    },
    {
      title: 'Draa Valley',
      slug: { current: 'draa-valley' },
      description: `The Draa Valley is Morocco's longest oasis valley, dotted with palm groves, kasbahs, and Berber villages. Drive through scenic landscapes, explore fortified kasbahs, and photograph iconic desert scenes along the way from Merzouga or Erg Chigaga to Ouarzazate.`,
      highlights: [
        'Longest oasis valley in Morocco',
        'Palm groves',
        'Ancient kasbahs',
        'Berber villages',
        'Scenic landscapes',
        'Historic fortifications',
      ],
      activities: [
        'Scenic drives',
        'Kasbah exploration',
        'Photography',
        'Village visits',
        'Oasis walks',
      ],
      seoKeywords: 'Draa Valley Morocco, palm oasis tours, kasbah photography Morocco, Sahara Desert scenic drive',
      order: 3,
    },
    {
      title: 'Ziz Valley',
      slug: { current: 'ziz-valley' },
      description: `Ziz Valley is famous for its lush palm groves, historic kasbahs, and traditional Berber villages. Travelers passing through often stop to explore the charming villages, take photos of the endless palms, and experience local life before reaching the Sahara Desert.`,
      highlights: [
        'Lush palm groves',
        'Historic kasbahs',
        'Traditional Berber villages',
        'Endless palm trees',
        'Local life experiences',
      ],
      activities: [
        'Village exploration',
        'Photography',
        'Kasbah visits',
        'Local culture immersion',
      ],
      seoKeywords: 'Ziz Valley Morocco, Berber villages Morocco, desert oasis tours, Erg Chebbi route',
      order: 4,
    },
    {
      title: 'Todra Gorge',
      slug: { current: 'todra-gorge' },
      description: `Todra Gorge offers breathtaking cliffs, palm-lined canyons, and hiking opportunities. Perfect for photography, trekking, and adventure lovers, the gorge provides a dramatic contrast to the surrounding desert landscapes.`,
      highlights: [
        'Breathtaking cliffs',
        'Palm-lined canyons',
        'Hiking opportunities',
        'Dramatic landscapes',
        'Photography spots',
      ],
      activities: [
        'Hiking',
        'Photography',
        'Rock climbing',
        'Canyon exploration',
      ],
      seoKeywords: 'Todra Gorge Morocco, Todra Gorge trekking, desert canyon Morocco, Sahara adventure photography',
      order: 5,
    },
    {
      title: 'Dades Valley',
      slug: { current: 'dades-valley' },
      description: `Known as the Valley of a Thousand Kasbahs, Dades Valley features winding roads, rock formations, and traditional Berber villages. Explore hiking trails, panoramic viewpoints, and desert landscapes along your journey to the Sahara.`,
      highlights: [
        'Valley of a Thousand Kasbahs',
        'Winding roads',
        'Rock formations',
        'Traditional Berber villages',
        'Panoramic viewpoints',
      ],
      activities: [
        'Hiking',
        'Kasbah exploration',
        'Photography',
        'Scenic drives',
      ],
      seoKeywords: 'Dades Valley Morocco, Atlas Mountains trekking, Berber villages Morocco, Morocco desert gorges',
      order: 6,
    },
    {
      title: 'Ait Ben Haddou',
      slug: { current: 'ait-ben-haddou' },
      description: `A UNESCO World Heritage site, Ait Ben Haddou Kasbah is one of Morocco's most famous historic landmarks and a film location for many international movies. Explore the fortified village, walk along its ancient streets, and capture stunning desert backdrop photography.`,
      highlights: [
        'UNESCO World Heritage site',
        'Historic kasbah',
        'Film location',
        'Fortified village',
        'Ancient architecture',
      ],
      activities: [
        'Historic site exploration',
        'Photography',
        'Film location tours',
        'Cultural immersion',
      ],
      seoKeywords: 'Ait Ben Haddou Morocco, UNESCO kasbah Morocco, Morocco film location, Sahara Desert excursions',
      order: 7,
    },
    {
      title: 'Ouarzazate',
      slug: { current: 'ouarzazate' },
      description: `Known as the "Gateway to the Desert", Ouarzazate is a hub for desert travelers and film enthusiasts. Visit kasbahs, desert landscapes, and local markets. Explore nearby Ait Ben Haddou, desert studios, and enjoy a base for Sahara Desert excursions.`,
      highlights: [
        'Gateway to the Desert',
        'Film capital of Morocco',
        'Historic kasbahs',
        'Film studios',
        'Desert travel hub',
      ],
      activities: [
        'Kasbah visits',
        'Film studio tours',
        'Market exploration',
        'Desert excursions',
      ],
      seoKeywords: 'Ouarzazate Morocco, Sahara Desert gateway, Moroccan kasbah tours, desert travel hub Morocco',
      order: 8,
    },
    {
      title: 'Rissani Market',
      slug: { current: 'rissani-market' },
      description: `Rissani is the traditional market town near Merzouga, offering a glimpse into authentic Berber life. Explore spice markets, dates, handcrafted goods, and vibrant souks that reflect the heart of Moroccan desert culture.`,
      highlights: [
        'Traditional market town',
        'Spice markets',
        'Date markets',
        'Handcrafted goods',
        'Vibrant souks',
        'Authentic Berber culture',
      ],
      activities: [
        'Market exploration',
        'Shopping',
        'Cultural immersion',
        'Local food tasting',
      ],
      seoKeywords: 'Rissani Morocco, Merzouga market tours, Berber souks, Moroccan desert culture',
      order: 9,
    },
    {
      title: 'Midelt & Atlas Mountains',
      slug: { current: 'midelt-atlas-mountains' },
      description: `Midelt lies in the Middle Atlas Mountains, known for cedar forests, scenic landscapes, and Berber villages. It's a perfect stopover for travelers heading to the Sahara Desert from Fes or Marrakech, offering trekking, photography, and authentic Moroccan cultural experiences.`,
      highlights: [
        'Middle Atlas Mountains',
        'Cedar forests',
        'Scenic landscapes',
        'Berber villages',
        'Mountain views',
      ],
      activities: [
        'Trekking',
        'Photography',
        'Village visits',
        'Mountain exploration',
      ],
      seoKeywords: 'Midelt Morocco, Middle Atlas Mountains, Berber villages Morocco, Sahara Desert route, Atlas mountain trekking',
      order: 10,
    },
  ]
}

